apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kube-a61f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kube-a61f"
  template:
    metadata:
      labels:
        app: "kube-a61f"
    spec:
      containers:
        - name: "kube-a61f"
          image: "simple2frontend.azurecr.io/kube"
          ports:
          - containerPort: 8080