on: [push]
jobs:
  backend-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: simple2frontend.azurecr.io
        username: ${{ secrets.acr_simple2frontend_username }}
        password: ${{ secrets.acr_simple2frontend_password }}
        
    - name: Build with Gradle
      working-directory: './backend'
      run: ./gradlew build
    
    - name: Build and push image to ACR
      working-directory: './backend'
      id: build-image
      run: |
        docker build -t simple2frontend.azurecr.io/kube-backend:${{ github.sha }} ./ --label dockerfile-path=backend/Dockerfile
        docker push simple2frontend.azurecr.io/kube-backend:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kube_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ingress-basic | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ingress-basic`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ingress-basic
        container-registry-url: simple2frontend.azurecr.io
        container-registry-username: ${{ secrets.acr_simple2frontend_username }}
        container-registry-password: ${{ secrets.acr_simple2frontend_password }}
        secret-name: kubedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ingress-basic
        manifests: |
          manifests/backend-deployment.yml
        images: |
          simple2frontend.azurecr.io/kube-backend:${{ github.sha }}
        imagepullsecrets: |
          kubedockerauth
